name: waltdisneyworld
version: 1.0
main: nl.joekoei.core.Core
api-version: 1.13
commands:
  ridecounter:
    description: HAHAHA
  magicband:
    description: oofie poofie
  control:
    description: Oofie Poofie
  spacemountain:
    description: oof poof