package eu.magicparksmc.magickingdom.fantasyland;

public class FantasylandList {
	enum fantasyland {
		BIBBIDI_BOBBIDI_BOUTIQUE, BIG_TOP_SOUVENIRS;
	}

	enum fantasylandRides {
		ITS_A_SMALL_WORLD, PETER_PANS_FLIGHT, PRINCE_CHARMING_REGAL_CARROUSEL, THE_MANY_ADVENTURES_OF_WINNIE_THE_POOH,
		MAD_TEA_PARTY, SEVEN_DWARFS_MINE_TRAIN, JOURNEY_OF_THE_LITTLE_MERMAID, DUMBO_THE_FLYING_ELEPHANT,
		WALT_DISNEY_WORLD_RAILROAD, THE_BARNSTORMER;
	}

	enum fantasylandAttractions {
		MICKEYS_PHILHARMAGIC, ENCHANTED_TALES_WITH_BELLE, PRINCESS_FAIRYTALE_HALL, FAIRYTALE_GARDEN, ARIELS_GROTTO,
		CASEY_JR_SPLASH_N_SOAK_STATION, PETES_SILLY_SIDESHOW;
	}

	enum fantasylandRestaurants {
		PINOCCHIO_VILLAGE_HAUS, CINDERELLAS_ROYAL_TABLE, THE_FRIARS_NOOK, STORYBOOK_TREATS, BE_OUR_GUEST_RESTAURANT,
		GASTONS_TAVERN, CHESHIRE_CAFE, PRINCE_ERICS_VILLAGE_MARKET;
	}
}